version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .development.env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    ports:
      - 5432
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always